name: ci

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Latest GCC
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-12
      - name: Install Google Test
        run: sudo apt-get update && sudo apt-get install -y libgtest-dev cmake          
      - name: Update Compiler Alternatives
        run: |
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 12
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B build -DHAKO_PDU_ENDPOINT_BUILD_TESTS=ON

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build
